channels:
  - ccpi
  - conda-forge
  - defaults
dependencies:
  - iris=3.0.1
  - netcdf4=1.5.6
  - pip=21.0.1
  - pyhdf=0.10.2
  - python-dateutil=2.8.1
  - python-magic=0.4.22
  - requests=2.25.1
  - xarray=0.17.0
  - xmltodict=0.12.0
