channels:
  - ccpi
  - conda-forge
  - defaults
dependencies:
  - iris=3.0.1=py38h50d1736_1
  - netcdf4=1.5.6=nompi_py38h1f593c7_100
  - pip=21.0.1=pyhd8ed1ab_0
  - pyhdf=0.10.2=py38hedab4a0_2
  - python-dateutil=2.8.1=py_0
  - python-magic=0.4.22=py38h50d1736_1
  - requests=2.25.1=pyhd3deb0d_0
  - xarray=0.17.0=pyhd8ed1ab_0
  - xmltodict=0.12.0=py_0